version: 2.1
orbs:
  hello: circleci/hello-build@0.0.5
workflows:
  "Hello Workflow":
    jobs:
      - hello/hello-build

commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>
