version: 2.1

parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

workflows:
  version: 2.1
  test:
    when: << pipeline.parameters.GHA_Action >>
    jobs:
      - approved_pr_job

jobs:
  approved_pr_job:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The conditional step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
