version: 2.1
parameters:
  GHA_Actor:
    type: string
    default: ""
  GHA_Action:
    type: string
    default: ""
  GHA_Event:
    type: string
    default: ""
  GHA_Meta:
    type: string
    default: ""

jobs:
  approved_pr_job:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The Second/Conditional Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
  test:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The First Step
          command: |
            echo 'Hello There!'
workflows:
  test:
    jobs:
      - test
  when: << pipeline.parameters.GHA_Action >>
  approved_pr_job:
    jobs:
      - approved_pr_job
