version: 2.1

jobs:
  - approved_pr_job:
    commands:
      sayhello:
        description: "A very simple command for demonstration purposes"
        parameters:
          to:
            type: string
            default: "Hello World"
        steps:
          - run: echo << parameters.to >>
