on:
  pull_request:
    types: [opened, reopened, synchronize, assigned, edited]
jobs:
  trigger-circleci:
    # if: "contains(github.event.pull_request.labels.*.name, 'bug')"
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Pull Request
        id: run-ui-tests
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
