on:
  pull_request:
    types: labeled

jobs:
  approved_pr_job:
    if: "contains(github.event.pull_request.labels.*.name, 'approved_pr_job')"
    runs-on: ubuntu-latest
    steps:
      - name: action name
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0.4
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
