on:
  pull_request:
    types: [opened, reopened, synchronize, assigned, edited]
    paths:
      - "**.js"
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Pull Request
        id: run-ui-tests
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        outputs:
        sum: # id of the output
        description: "The sum of the inputs"
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
