# on:
#   push:
#     paths:
#       - "**.js"

on:
  pull_request:
    types:
      - labeled

jobs:
  trigger-circleci:
    if: "contains(github.event.pull_request.labels.*.name, 'bug')"
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Pull Request
        id: run-ui-tests
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
