on:
  pull_request:
    types: [edited]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: CircleCI Trigger on Pull Request
        id: some custom id
        uses: CircleCI-Public/trigger-circleci-pipeline-action@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
